### ISSUE TITLE
I encountered it while playing a small game Lssues

### ISSUE THREAD

**Issue by ghost** [RisottoMan/AutoEvent#106]
[2024-10-31 18:44:19.632 +08:00] >>> ev run cs
[2024-10-31 18:44:19.671 +08:00] You need a map de_dust2 to run a mini-game.

**Comment by kldhsh123** [comment]
检查一下地图文件有没有正确添加
Check that the map file has been added correctly

**Comment by RisottoMan** [comment]
I see that many people don't understand the meaning of this error, so I've made it more informative:

"You need to download the map {name} to run this mini game."
"Download and install Schematics.tar.gz from the github.";
