### ISSUE TITLE
[Request] Remove blinding effect from Jailbird secondary fire from tag gamemode

### ISSUE THREAD

**Issue by emshov74** [RisottoMan/AutoEvent#107]
The blinding from jailbird secondary punishes players too much, if you could get rid of it in any way that would be nice

**Comment by RisottoMan** [comment]
Hello. Can you describe step by step how this bug appears?

**Comment by emshov74** [comment]
Hi, this is not really a bug but a feature working as intended (but annoying for the minigame). I will document it for you anyways:
1. Queue the tag minigame;
2. Hit a D-Class (runner) as Scientist (tagger) with the charged attack (Right-Click) of the Jailbird;
3. Upon being hit with this charged attack the D-Class becomes a tagger (Scientist), but retains a blinding effect for a few seconds because of the charged hit. This effect has been received as annoying by players within my community, as you cant see anything for a few seconds in a game where every second counts.

**Comment by RisottoMan** [comment]
Can you additionally make a short video? I will try to fix the bug by the weekend

**Comment by emshov74** [comment]
Heres a vid:
https://streamable.com/ejqwtx

**Comment by RisottoMan** [comment]
Thanks

**Comment by RisottoMan** [comment]
If you know more bugs, please write

**Comment by RisottoMan** [comment]
![image](https://github.com/user-attachments/assets/8b8ac17c-758b-4a12-818b-24e08e173ef7)

**Comment by RisottoMan** [comment]
Fixed in new release.
