### ISSUE TITLE
Musical Chairs [chair] Problem

### ISSUE THREAD

**Issue by Electro7777** [RisottoMan/AutoEvent#118]
The logic is flawed.

Some circles remain unoccupied, and multiple players standing on the same circle don't die. Only the first player to step on the circle should survive, but instead, all of them remain alive. In some cases, players who aren’t standing on any circle also survive.

Additionally, the minigame malfunctions when only a few players are left. While the music continues to play, the circles stop changing positions and colors.

**Comment by RisottoMan** [comment]
The bug has been fixed in the new version. Wait for the release.
