### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by LaFesta1749** [RisottoMan/AutoEvent#2]
Will there be an update to exiled 7 and SCP:SL 13.0 ?

**Comment by RisottoMan** [comment]
I could fix the plugin, but it doesn't make sense at the moment. MapEditorReborn is used in the project and will spawn all primitives in white. The problem is with the shaders. The developers of the NW game should fix it, otherwise the plugin is dead.

**Comment by LaFesta1749** [comment]
Once again Northwood breaks the game... Lovely
