### ISSUE TITLE
Different gamemodes? [question]

### ISSUE THREAD

**Issue by LaFesta1749** [RisottoMan/AutoEvent#3]
Hello,
I saw a lot of photos of different maps/gamemodes in the photos folder and I was wondering if those were planned or not yet implemented?

I would love to help with the development of the maps if needed.

Thanks

**Comment by RisottoMan** [comment]
Write me in discord

**Comment by LaFesta1749** [comment]
> Write me in discord

I don't know what your discord it.
Here's mine so you can add me: ThruBeing#0554
