### ISSUE TITLE
Events not starting

### ISSUE THREAD

**Issue by LaFesta1749** [RisottoMan/AutoEvent#4]
![image](https://github.com/KoT0XleB/AutoEvent-Exiled/assets/1494298/65d1fe76-2602-4f5a-b2ba-c4348d4c8b7a)

![image](https://github.com/KoT0XleB/AutoEvent-Exiled/assets/1494298/3b5f892c-e94f-48bb-8991-bf937ce596ea)

**Comment by RisottoMan** [comment]
> ![image](https://github.com/KoT0XleB/AutoEvent-Exiled/assets/1494298/65d1fe76-2602-4f5a-b2ba-c4348d4c8b7a)
> 
> ![image](https://github.com/KoT0XleB/AutoEvent-Exiled/assets/1494298/3b5f892c-e94f-48bb-8991-bf937ce596ea)
> 

Write me in discord

**Comment by LaFesta1749** [comment]
> Write me in discord

I don't know what your discord it.
Here's mine so you can add me: ThruBeing#0554
