### ISSUE TITLE
Request of changes in 2 events

### ISSUE THREAD

**Issue by denys767** [RisottoMan/AutoEvent#40]
1. "airstrike" should end when one person is alive
2. "zombie3": there aren't ANY zombies

**Comment by Redforce04** [comment]
> 1. "airstrike" should end when one person is alive
> 2. "zombie3": there aren't ANY zombies


Zombie 3 should be fixed now.
The logic behind Airstrike is it's more like a puzzle. In order to survive, you would have to survive 5 rounds. I will implement a config option to toggle last-alive is winner.

**Comment by Redforce04** [comment]
Zombie 3 - Fixed
Airstrike - now has a config you can toggle to end on the last player.
