### ISSUE TITLE
Can't run atomic escape.

### ISSUE THREAD

**Issue by denys767** [RisottoMan/AutoEvent#41]
Can't run atomic escape on beta because it is impossible to run command `ev run atomic escape`

**Comment by LennyFirst0** [comment]
Correct command: `ev run escape`
Please, look `ev list` carefully

**Comment by Redforce04** [comment]
This was a bug which we fixed. It was due to a translation issue. A fix will be out soon.

> Can't run atomic escape on beta because it is impossible to run command `ev run atomic escape`
