### ISSUE TITLE
atomic escape doesn't reset nuke timer or doors

### ISSUE THREAD

**Issue by itsloley** [RisottoMan/AutoEvent#53]
when you start atomic escape the timer doesn't reset back to default, meaning that if it uses the default config and starts at T-90 seconds and finish it, it resumes at T-30 seconds so if you play it again, the nuke will explode

the event also does not reset the doors back to normal, potentially disrupting other custom events that place the player inside of the facility and requiring a server restart in order to 'set things back to normal' to play a regular round of the game

**Comment by Redforce04** [comment]
This makes sense. I will take a look at it. In general the nuke tends to behave weirdly, as it has a lot of client sided events that it triggers.
