### ISSUE TITLE
Lobby Event Issues

### ISSUE THREAD

**Issue by Xect0r** [RisottoMan/AutoEvent#84]
It seems the Lobby is a bit rough, just installed AutoEvent on a freshly downloaded server and I noticed a few issues ranging from objects being too far away from the wall preventing people from choosing or stepping on the selector to texts and primitives being also far away from the walls.

I think the most noticeable are:

- Death Line
- Among Us (Can barely step on the platform to select it)
- ZM2
- ZM3

Additionally, it seems that when selecting some of them you might find yourself with a console full of errors (I tested this with just a player as I was translating things to my liking when I stumbled upon them, I'm unsure if that might have caused it):
```
[Warning] [AutoEvent] Caught an exception at Event.ProcessFrame().
```

This also raised the question: What's the correct way to use the Lobby event? I noticed that when selecting an event it simply says that the Lobby event is already running.

**Comment by RisottoMan** [comment]
If possible, write to me in the discord. I'm ignoring github, as the more convenient option is to just talk in the discord.
