### ISSUE TITLE
Missing folders aren't being generated when there are other ones already present.

### ISSUE THREAD

**Issue by EsserGaming** [RisottoMan/AutoEvent#95]
So when there is a folder already in the `/EXILED/Configs/AutoEvent/` folder, the plugin will not generate the other folders, including their respective files (configs, events).

Here's the conversation that I brought up [on the EXILED Discord server](https://discord.com/channels/656673194693885975/1154287924016336946/1263340000834093096).

**Comment by Redforce04** [comment]
Plugin.cs#134 is the line where directories are created. If debug mode is enabled there may be logs. An exception for any of the folders could prevent other folders from being generated. The exception could be from file permissions.

**Comment by Redforce04** [comment]
https://github.com/RisottoMan/AutoEvent/blob/main/AutoEvent/Plugin.cs#L134

**Comment by Redforce04** [comment]
That line calls this method.

CreateDirectoryIfNotExists

https://github.com/RisottoMan/AutoEvent/blob/main/AutoEvent/Plugin.cs#L194

**Comment by Redforce04** [comment]
According to Esser after enabling debug mode, the problem went away. This most likely indicates that there is a bug in the debug logger that is suppressed unless debug mode is enabled. This is the first time the debug logger method is called.

**Comment by RisottoMan** [comment]
Closed, I no longer support AutoEvent.
