### ISSUE TITLE
No lighting animation [animation of intensity and range changes does not work]

### ISSUE THREAD

**Issue by Xlebik-cloud** [RisottoMan/AutoEvent#97]
**In short, the lighting animation does not work.** I added an animation of intensity changes to one of the maps for the auto event. It works if you load the map using the "mp create" command, **but if you run an auto-event with this map, the animation of the light does not work.**

**Comment by Redforce04** [comment]
This is likely because for simplicity, Auto Event utilizes a custom stripped version of Map Editor. It is not guaranteed to implement the same things as the more it implements the more overhead on our end.

**Comment by RisottoMan** [comment]
I don't plan to fix it.
